export const allMatches = 3;

export const data = [
  {
    puuid: "",
    name: "Djalti",
    matchesPlayed: 3,
    matchesWon: 2,
    matchesLost: 1,
    matchesDrawn: 0,
  },
  {
    puuid: "",
    name: "Aymene",
    matchesPlayed: 3,
    matchesWon: 3,
    matchesLost: 0,
    matchesDrawn: 0,
  },
  {
    puuid: "",
    name: "Croco",
    matchesPlayed: 3,
    matchesWon: 3,
    matchesLost: 0,
    matchesDrawn: 0,
  },
  {
    puuid: "",
    name: "Oscar",
    matchesPlayed: 3,
    matchesWon: 0,
    matchesLost: 3,
    matchesDrawn: 0,
  },
  {
    name: "xMarXMaN",
    puuid: "",
    matchesPlayed: 2,
    matchesWon: 2,
    matchesLost: 0,
    matchesDrawn: 0,
  },
  {
    name: "Sugar Cakes",
    puuid: "",
    matchesPlayed: 3,
    matchesWon: 2,
    matchesLost: 1,
    matchesDrawn: 0,
  },
  {
    name: "Yellow",
    puuid: "",
    matchesPlayed: 3,
    matchesWon: 0,
    matchesLost: 3,
    matchesDrawn: 0,
  },
  {
    name: "xLyes",
    puuid: "",
    matchesPlayed: 3,
    matchesWon: 1,
    matchesLost: 2,
    matchesDrawn: 0,
  },
  {
    name: "Sohaib",
    puuid: "",
    matchesPlayed: 3,
    matchesWon: 0,
    matchesLost: 3,
    matchesDrawn: 0,
  },
  {
    name: "Noui",
    puuid: "",
    matchesPlayed: 1,
    matchesWon: 1,
    matchesLost: 0,
    matchesDrawn: 0,
  },
  {
    name: "MellioDas",
    puuid: "",
    matchesPlayed: 1,
    matchesWon: 0,
    matchesLost: 1,
    matchesDrawn: 0,
  },
  {
    name: "Fortayer",
    puuid: "",
    matchesPlayed: 2,
    matchesWon: 2,
    matchesLost: 0,
    matchesDrawn: 0,
  },
];
